"""LaminaRWAToken + LaminaFactory contract interactions.

Replaces server/hedera/token.py — identical function signatures,
EVM implementation via web3.py.

Hedera → EVM mapping:
  create_token()       → Factory.deployAsset()         (token + audit topic in 1 tx)
  create_account()     → eth_account.Account.create()  (generate ETH keypair)
  grant_kyc()          → LaminaRWAToken.grantKYC()
  revoke_kyc()         → LaminaRWAToken.revokeKYC()
  freeze_account()     → LaminaRWAToken.freeze()
  unfreeze_account()   → LaminaRWAToken.unfreeze()
  mint_tokens()        → LaminaRWAToken.mint()
  burn_tokens()        → LaminaRWAToken.burn()          (treasury burns own supply)
  transfer_tokens()    → LaminaRWAToken.transfer()      (compliance hooks auto-enforce)
  wipe_tokens()        → LaminaRWAToken.forceBurn()     (maturity settlement)
  transfer_hbar()      → USDC.transfer()                (UPGRADE: coupons in USDC)
"""

import json
import logging
from pathlib import Path

from eth_account import Account
from web3 import Web3

from server.arbitrum.client import (
    get_web3, get_operator_address, get_operator_private_key,
    build_and_send, next_nonce,
)
from server.config import get_settings

logger = logging.getLogger(__name__)

# ─── ABI loading ─────────────────────────────────────────────────────────────
_ABI_DIR = Path(__file__).parent.parent.parent / "contracts" / "abi"

def _load_abi(name: str) -> list:
    """Load ABI from contracts/abi/<name>.json (generated by deploy script)."""
    path = _ABI_DIR / f"{name}.json"
    if not path.exists():
        raise FileNotFoundError(
            f"ABI file not found: {path}\n"
            "Run contracts/scripts/deploy.py first to compile and deploy contracts."
        )
    with open(path) as f:
        return json.load(f)


# Lazy-loaded contract instances
_factory_contract = None
_token_abi = None
_erc20_abi = None   # minimal ERC-20 ABI for USDC transfers


def _get_factory():
    global _factory_contract
    if _factory_contract is None:
        settings = get_settings()
        w3 = get_web3()
        _factory_contract = w3.eth.contract(
            address=Web3.to_checksum_address(settings.factory_address),
            abi=_load_abi("LaminaFactory"),
        )
    return _factory_contract


def _get_token_abi():
    global _token_abi
    if _token_abi is None:
        _token_abi = _load_abi("LaminaRWAToken")
    return _token_abi


def _get_token_contract(token_address: str):
    w3 = get_web3()
    return w3.eth.contract(
        address=Web3.to_checksum_address(token_address),
        abi=_get_token_abi(),
    )


_MINIMAL_ERC20_ABI = [
    {
        "inputs": [
            {"internalType": "address", "name": "to",     "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
        ],
        "name": "transfer",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
]


# ─── Account ─────────────────────────────────────────────────────────────────

def create_account(initial_balance_hbar: int = 10) -> tuple[str, str]:
    """Generate a new ETH wallet keypair.

    The `initial_balance_hbar` param is kept for API compatibility with
    the Hedera version (it had meaning there; on EVM we ignore it — the
    operator can fund new wallets separately if needed).

    Returns (address, private_key_hex).
    """
    acct = Account.create()
    addr = acct.address
    key  = acct.key.hex()
    logger.info(f"Created EVM account: {addr}")
    return addr, key


# ─── Token deployment ─────────────────────────────────────────────────────────

def create_token(
    name: str,
    symbol: str,
    decimals: int = 2,
    initial_supply: int = 0,
    max_supply: int = 0,        # kept for API compat; ERC-20 has no built-in max
    asset_type: str = "bond",
    jurisdiction: str = "US",
) -> tuple[str, str]:
    """Deploy a new LaminaRWAToken via LaminaFactory.

    Returns (token_address, topic_id_hex) — the audit topic is created
    atomically in the same factory call.

    NOTE: differs from hedera/token.py which returned only token_id.
    The caller (lifecycle.py) receives both values now.
    """
    w3       = get_web3()
    settings = get_settings()
    factory  = _get_factory()
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = factory.functions.deployAsset(
        name,
        symbol,
        initial_supply,
        decimals,
        asset_type,
        jurisdiction,
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      4_000_000,
        "gasPrice": w3.eth.gas_price,
    })

    tx_hash = build_and_send(w3, tx, pk)

    # Read token address and topic from the AssetDeployed event
    receipt = w3.eth.get_transaction_receipt(tx_hash)
    factory_contract = _get_factory()
    events = factory_contract.events.AssetDeployed().process_receipt(receipt)

    if not events:
        raise RuntimeError(f"AssetDeployed event not found in receipt {tx_hash}")

    evt          = events[0]["args"]
    token_address = evt["tokenAddress"]
    topic_id      = evt["topicId"].hex()  # bytes32 → hex string

    logger.info(f"Deployed token {symbol} → {token_address}  topic={topic_id}")
    return token_address, topic_id


# ─── Mint / Burn ──────────────────────────────────────────────────────────────

def mint_tokens(token_address: str, amount: int) -> str:
    """Mint additional tokens to the operator (treasury). Returns tx_hash."""
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.mint(
        Web3.to_checksum_address(operator), amount
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      200_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Minted {amount} tokens for {token_address}")
    return tx_hash


def burn_tokens(token_address: str, amount: int) -> str:
    """Burn tokens from the treasury (operator) address. Returns tx_hash."""
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.burn(amount).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      200_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Burned {amount} tokens for {token_address}")
    return tx_hash


# ─── KYC ─────────────────────────────────────────────────────────────────────

def grant_kyc(token_address: str, account_address: str) -> str:
    """Grant KYC to an address for a specific token. Returns tx_hash."""
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.grantKYC(
        Web3.to_checksum_address(account_address)
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Granted KYC: {account_address} on {token_address}")
    return tx_hash


def revoke_kyc(token_address: str, account_address: str) -> str:
    """Revoke KYC from an address. Returns tx_hash."""
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.revokeKYC(
        Web3.to_checksum_address(account_address)
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Revoked KYC: {account_address} on {token_address}")
    return tx_hash


# ─── Freeze / Unfreeze ───────────────────────────────────────────────────────

def freeze_account(token_address: str, account_address: str) -> str:
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.freeze(
        Web3.to_checksum_address(account_address)
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Froze account {account_address} for {token_address}")
    return tx_hash


def unfreeze_account(token_address: str, account_address: str) -> str:
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.unfreeze(
        Web3.to_checksum_address(account_address)
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Unfroze account {account_address} for {token_address}")
    return tx_hash


# ─── Transfers ────────────────────────────────────────────────────────────────

def associate_token(account_address: str, token_address: str, account_private_key: str | None = None) -> str:
    """No-op on EVM — token association is a Hedera-only concept.

    Kept for API compatibility with compliance.py which calls this during
    whitelist onboarding. Returns empty string.
    """
    logger.debug(f"associate_token: no-op on EVM for {account_address}")
    return ""


def transfer_tokens(
    token_address: str,
    from_address: str,
    to_address: str,
    amount: int,
    decimals: int = 2,
) -> str:
    """Transfer tokens from operator treasury to an investor. Returns tx_hash.

    The compliance hooks inside LaminaRWAToken._update() auto-enforce
    KYC and freeze state — no pre-flight check needed here.
    """
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.transfer(
        Web3.to_checksum_address(to_address), amount
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),   # must be treasury (from_address)
        "nonce":    next_nonce(w3, operator),
        "gas":      150_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Transferred {amount} of {token_address} → {to_address}")
    return tx_hash


def wipe_tokens(token_address: str, account_address: str, amount: int) -> str:
    """Force-burn tokens from a holder at maturity (= HTS wipe key). Returns tx_hash."""
    w3       = get_web3()
    settings = get_settings()
    token    = _get_token_contract(token_address)
    operator = get_operator_address()
    pk       = get_operator_private_key()

    tx = token.functions.forceBurn(
        Web3.to_checksum_address(account_address),
        amount,
        "maturity_settlement",
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      150_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"Force-burned {amount} tokens from {account_address}")
    return tx_hash


# ─── USDC coupon payments (replaces HBAR transfer) ───────────────────────────

def transfer_hbar(to_address: str, amount_tinybars: int) -> str:
    """Transfer USDC to a holder as coupon payment.

    API-compatible with the Hedera version (same function name, same params).
    amount_tinybars is reinterpreted as USDC micro-units (6 decimals).

    UPGRADE: Hedera paid coupons in HBAR (gas token).
             Robinhood Chain pays coupons in USDC — USD-denominated,
             exactly what institutional investors expect.
    """
    return transfer_usdc(to_address, amount_tinybars)


def transfer_usdc(to_address: str, amount_units: int) -> str:
    """Transfer USDC from operator to recipient. amount_units in USDC smallest unit (6 dec).

    Returns tx_hash.
    """
    settings = get_settings()
    if not settings.usdc_address:
        logger.warning("USDC_ADDRESS not configured — coupon payment skipped")
        return "usdc_not_configured"

    w3       = get_web3()
    operator = get_operator_address()
    pk       = get_operator_private_key()

    usdc = w3.eth.contract(
        address=Web3.to_checksum_address(settings.usdc_address),
        abi=_MINIMAL_ERC20_ABI,
    )

    tx = usdc.functions.transfer(
        Web3.to_checksum_address(to_address), amount_units
    ).build_transaction({
        "chainId":  settings.chain_id,
        "from":     Web3.to_checksum_address(operator),
        "nonce":    next_nonce(w3, operator),
        "gas":      100_000,
        "gasPrice": w3.eth.gas_price,
    })
    tx_hash = build_and_send(w3, tx, pk)
    logger.info(f"USDC coupon: {amount_units} units → {to_address}")
    return tx_hash


def get_token_balance(token_address: str, account_address: str) -> int:
    """Read ERC-20 balanceOf. Utility for balance sync."""
    token = _get_token_contract(token_address)
    return token.functions.balanceOf(
        Web3.to_checksum_address(account_address)
    ).call()
